/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ArDzsZaMicU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Landing() {
  const [isNavOpen, setIsNavOpen] = useState(false)
  return (
    <div className="flex flex-col min-h-[100dvh] max-w-5xl justify-center mx-auto items-center">
      <header className="px-6 h-14 flex items-center">
        <nav className="ml-auto flex gap-4 sm:gap-6 items-center">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Projects
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 mx-auto max-w-7xl w-full px-6 ">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container">
              <div className="flex flex-col justify-center space-y-4 animate-fade-in">
                <div className="space-y-2 text-center">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none p-4">
                    Ryan Zhang
                  </h1>
                  <p className="text-muted-foreground md:text-xl text-center self-center">
                    Second year computer science student at UBC.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
                  <Link
                      href="https://linkedin.com/in/rmzhang"
                      rel="noopener noreferrer" target="_blank"
                      className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                      prefetch={false}>
                    Connect with me here!
                  </Link>
                </div>
              </div>
            {/* form*/}
              {/*<div className="rounded-xl bg-muted p-6 shadow-lg max-w-3xl">*/}
              {/*  <h2 className="text-2xl font-bold mb-4">Get in Touch</h2>*/}
              {/*  <form className="space-y-4">*/}
              {/*    <Input type="text" placeholder="Name" className="w-full"/>*/}
              {/*    <Input type="email" placeholder="Email" className="w-full"/>*/}
              {/*    <Textarea placeholder="Message" className="w-full" rows={4}/>*/}
              {/*    <Button type="submit" className="w-full">*/}
              {/*      Submit*/}
              {/*    </Button>*/}
              {/*  </form>*/}
              {/*</div>*/}
            </div>


        </section>
      </main>

    </div>
  )
}

function BriefcaseIcon(props) {
  return (
      <svg
          {...props}
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
      >
        <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>
        <rect width="20" height="14" x="2" y="6" rx="2"/>
      </svg>
  )
}
